config/routes.rb
Rails.application.routes.default_url_options[:host] = "localhost"
Rails.application.routes.draw do
  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  get 'home/index'
  root 'home#index'
  get 'order' => 'order#index', as: 'order'
  get 'welcome' => 'home#welcome', as: 'welcome'
  get 'enquiry' => 'home#contact', as: 'enquiry'
  get 'about' => 'home#about', as: 'about'
  get 'faq' => 'home#faq', as: 'faq'
  post 'create_order' => 'order#create_order', as: 'create_order'
  # get '/get_pincode_details', to: 'order#get_pincode_details', as: :get_pincode_details
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api do
    namespace :v1 do
      get '/test', to: 'pincode#test', as: :test
      get '/get_pincode_details', to: 'pincode#get_pincode_details', as: :get_pincode_details
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
	before_save :set_default_values, :set_order_number
	# attr_accessor :items_attributes
	has_many :order_items, :foreign_key => "order_id", :dependent => :delete_all
	accepts_nested_attributes_for :order_items, :allow_destroy => true
	validates_presence_of :delivery_zipcode, :delivery_address

	def set_default_values
	    usr_id = 1
	    self.created_user_id = usr_id if self.new_record?
	    self.updated_user_id = usr_id if self.changed?
	end

	def set_order_number
	    next_id = Order.maximum('id')
	    self.order_number = (Time.now.strftime('%Y%m%d') + ("%.5i" %next_id)).to_s
	end

    def self.percent(num, percentage)
      	tax = (num * percentage) / 100
    end

    def self.order_items(sku_code, quantity, price, amt)
    	self.order_items.create!(sku_code: sku_code, quantity: quantity, price: price, total_amount: amt)
    end

    def self.create_your_order(pincode, state, city, area, address, tax, total_amount)
    	self.create!(delivery_zipcode: pincode, delivery_state: state, delivery_city: city, delivery_area: area, delivery_address: address, tax: tax, total_amount: total_amount)
    end

    def self.save_quantity(state_name, sku_code, quantity, total_quantity)
      begin
        available_stock = ""
        state = PrefectureCode.find_by_name(state_name)
        if state.ew_flag == '東'
          warehouse_code = 'EAST'
        else
          warehouse_code = 'WEST'
        end

        code = SoukoZaiko.find_by_warehouse_code_and_sku_code_and_stock_type(warehouse_code, sku_code, "01")
        code1 = SoukoZaiko.where(sku_code: sku_code, stock_type: "01")
        total_code1 = code1[0][:stock] + code1[1][:stock]
        sum = 0
        code2 = SoukoZaiko.where(warehouse_code: warehouse_code, sku_code: sku_code, stock_type: "02")
        if code2.present?
          code2.each do |key, value|
            sum += key[:stock]
          end
        end
        new_sum = total_code1 - sum

        if code.present?
          if quantity <= code.stock
            if sum > 0
              sum1 = code.stock - sum
              if sum1 >= quantity
                SoukoZaiko.new_souko_zaiko(warehouse_code, sku_code, "02", quantity)
              elsif sum1 < quantity
                SoukoZaiko.check_zaiko(warehouse_code, sku_code, quantity, sum1)
              end
            else
              SoukoZaiko.new_souko_zaiko(warehouse_code, sku_code, "02", quantity)
            end
          else
            if quantity > total_code1
              # redirect_to order_path, flash: {error: "Stock not available"}
            elsif quantity <= total_code1
              if sum > 0
              sum1 = code.stock - sum
                if sum1 >= quantity
                  SoukoZaiko.new_souko_zaiko(warehouse_code, sku_code, "02", quantity)
                elsif sum1 < quantity
                  SoukoZaiko.check_zaiko(warehouse_code, sku_code, quantity, sum1)
                end
              elsif (sum == 0 && quantity <= total_code1)
                new_stock = quantity - code.stock
                if warehouse_code == 'EAST'
                  warehouse_code1 = 'WEST'
                elsif warehouse_code == 'WEST'
                  warehouse_code1 = 'EAST'
                end
                SoukoZaiko.new_souko_zaiko(warehouse_code, sku_code, "02", code.stock)
                SoukoZaiko.new_souko_zaiko(warehouse_code1, sku_code, "02", new_stock)
              else
                SoukoZaiko.new_souko_zaiko(warehouse_code, sku_code, "02", quantity)
              end
            end
          end
        else
          # redirect_to order_path, flash: {error: "stock not available."}
        end
      rescue => e
        raise ActiveRecord::Rollback
      end
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  skip_before_action :verify_authenticity_token
  # protect_from_forgery prepend: true, with: :exception
  protect_from_forgery with: :null_session
  before_action :authenticate_user!


    def index
      sku_code = SoukoZaiko.select(:sku_code).all
    end

    def create_order
      begin
        stock = []
        if params[:r].present?
          params[:r].each do |key, value|
            quantity = value[:quantity].gsub(',', '').to_i
            stock1 = SoukoZaiko.zaiko_stock(value[:sku_code], quantity)
            stock.push(stock1)
          end
        end

        av_stock = stock.uniq.join(', ')
        if av_stock == "available"
          amt = params[:r][:quantity].to_i * params[:r][:price].to_i
          tax = Order.percent(amt, 10)
          total_amount = amt + tax
          order = Order.create_your_order(params[:pincode], params[:state], params[:city], params[:area], params[:address], tax, total_amount)
          total = 0
          total_quantity = 0
          if params[:r].present?
            params[:r].each do |key, value|
              quantity = value[:quantity].gsub(',', '').to_i
              price = value[:price].gsub(',', '').to_i
              amt1 = quantity * price
              order.order_items.create!(sku_code: value[:sku_code], quantity: quantity, price: price, total_amount: amt1)
              total += amt1
              total_quantity += value[:quantity].gsub(',', '').to_i
              Order.save_quantity(params[:state],value[:sku_code],value[:quantity].gsub(',', '').to_i, total_quantity)
            end
          end
          total1 = total + amt
          new_order = Order.find_by_id(order.id)
          if new_order.nil?
          else
            new_order.update!(tax: Order.percent(total1, 10), total_amount: (total1 + Order.percent(total1, 10)))
            redirect_to order_path, flash: {success: 'Your order is successfully created'}
          end
        else
          redirect_to order_path, flash: {error: "Stock not available"}
        end
      rescue => e
        raise ActiveRecord::Rollback
      end
    end
end

app/views/order/_order.html.erb
<div id="content" style="padding-bottom: 100px;">
    <div class="container">
      <h2 class="h2">Your Address And Item Details</h2>
    </div>
    <div class="container">
        <%= form_with url: create_order_path do |f| %>
            <label for="pincode" class="lbl-font">Pincode</label>
            <input type="text" id="pincode" name="pincode" placeholder="Your pincode.." maxlength="7" required="" class="lbl-font only-number">

            <label for="state" class="lbl-font">State</label>
            <input type="text" id="state" name="state" placeholder="Your state.." required="" class="lbl-font">

            <label for="city" class="lbl-font">City</label>
            <input type="text" id="city" name="city" placeholder="Your city.." required="" class="lbl-font">

            <label for="area" class="lbl-font">Area</label>
            <input type="text" id="area" name="area" placeholder="Your area.." required="" class="lbl-font">

            <label for="address" class="lbl-font">Address</label>
            <input type="text" id="address" name="address" placeholder="Your address.." required="" class="lbl-font">

            <label class="lbl-font">Item Information</label>
            <table id="myTable">
                <thead class="remove_th_border">
                    <tr>
                        <th class="lbl-font number_border" style="width: 60px;"></th>
                        <th class="lbl-font" style="width: 700px;">Item Name</th>
                        <th class="lbl-font txt_border1" style="width: 20px;"></th>
                        <th class="lbl-font" style="width: 50px;">Item Quantity</th>
                        <th class="lbl-font txt_border1" style="width: 20px;"></th>
                        <th class="lbl-font" style="width: 150px;">Item Price</th>
                        <th class="lbl-font" style="width: 100px;text-align: center;">Total Price</th>
                        <th class="lbl-font" style="width: 100px;text-align: center;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <tr id="">
                        <td style="width: 60px;text-align: center;" class="ml-10 lbl-font number_border"><label>1</label></td>
                        <%= f.fields_for :order_items[1], @items do |item| %>
                            <% disabled_stock = SoukoZaiko.where(is_disable: 1, stock_type: "01").pluck(:sku_code) %>
                            <td style="width: 700px;"><%= item.collection_select "0[sku_code", SoukoZaiko.select('distinct on (sku_code) *'),:sku_code,:sku_code, class: 'lbl-font', disabled: disabled_stock %></td>
                            <td style="width: 20px;" class="txt_border1"></td>
                            <td style="width: 50px;"><%= item.text_field :quantity,id: "quantity" ,class: 'height-10 mt-0 mb-0 quantity lbl-font only-number number-seperator remove_border_outline', required:'', name: "[r]0[quantity]", maxlength: "3", placeholder: "0" %></td>
                            <td style="width: 20px;" class="txt_border1"></td>
                            <td style="width: 150px;"><%= item.text_field :price,id: "price" ,class: 'height-10 mt-0 mb-0 price lbl-font only-number number-seperator remove_border_outline', required:'', name: "[r]0[price]", maxlength: "4", placeholder: "0" %></td>
                            <td style="width: 100px;" class="txt_border"><%= item.text_field :total_amount,id: "total_amount" , name: "total_amount", placeholder: "0",class: 'height-10 mt-0 mb-0 total_amount tbox lbl-font' %></td>
                        <% end %>
                            <td style="width: 100px;" class="ml-10 lbl-font txt_border"><a href="javascript:void(0);" class="remove-row">Remove</a></td>
                    </tr>
                </tbody>
            </table>
            <span class="add_item"><a href="javascript:void(0);" class="add-field lbl-font" onclick="addField();">+ Add more item</a><br/></span>
            <div style="height: 100px !important;width: 300px;float: right;text-align: end">
                <label class="lbl-font">Total</label><label class="total lbl-cal lbl-font"></label><br/>
                <label class="lbl-font">TAX 10%</label><label class="tax lbl-cal lbl-font"></label><br/>
                <label class="lbl-font">Total Price</label><label class="total_price lbl-cal lbl-font"></label>
            </div>
            <br/><br/><br/>
            <input id = "submit" type="submit" value="Submit" class="lbl-font sbt-btn">
        <% end %>
    </div>
</div>